# Base image
FROM --platform=linux/amd64 node:18.15.0 as build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn

# Copy the rest of the application code
COPY . .

# Build the Angular app
RUN yarn build

#RUN find / -name "angular-errors.log" -exec cat -n {} \;
# Final image
FROM --platform=linux/amd64 nginx:alpine

# Copy the built app from the previous stage
COPY --from=build /app/dist/* /usr/share/nginx/html/

# Expose the default Nginx port
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
